# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 1
  start_block: 12369620
  contracts:
  - name: UniswapV3Factory
    address:
    - 0x1F98431c8aD98523631AE4a59f267346ea31F984
    handler: src/EventHandlers.ts
    events:
    - event: FeeAmountEnabled(uint24 indexed fee, int24 indexed tickSpacing)
    - event: OwnerChanged(address indexed oldOwner, address indexed newOwner)
    - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
rollback_on_reorg: false
